const DATA=["indices-all","global","fii-dii","breadth","radar","news","economy-pulse","crypto","stock-scores","preopen","candles"];
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const pct=n=>{n=Number(n)||0;return (n>0?"+":"")+n.toFixed(2)+"%"}; const num=n=>Number(n).toLocaleString("en-IN",{maximumFractionDigits:2});
const cache={};
async function load(name){const r=await fetch("./data/"+name+".json?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error(name+" "+r.status);cache[name]=await r.json();return cache[name]}
function fresh(ts){if(!ts)return"—";const d=new Date(ts);return isNaN(d)?"—":d.toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}
function card(name,obj){const p=Number(obj.change_pct??obj.chg_pct??obj.chg??0);return '<div class="index-card" data-index="'+esc(name)+'"><b>'+esc(name)+'</b><div class="price">'+num(obj.price)+'</div><small class="'+(p>=0?"up":"down")+'">'+pct(p)+' · '+(obj.source||"NSE")+'</small></div>'}
function sectorBucket(n){const s=String(n).toUpperCase();const m=[["IT",/\bIT\b|TECHNOLOGY/],["BANK",/BANK/],["FIN SERV",/FINANCIAL|FINSER|FIN SERVICE/],["AUTO",/AUTO/],["PHARMA",/PHARMA/],["HEALTHCARE",/HEALTH|HEALTHCARE/],["FMCG",/FMCG|CONSUMPTION/],["METAL",/METAL/],["ENERGY",/ENERGY/],["OIL & GAS",/OIL.*GAS/],["REALTY",/REALTY|REIT/],["MEDIA",/MEDIA/],["CHEMICALS",/CHEMICAL/],["CEMENT",/CEMENT/],["CONSUMER DURABLES",/CONSUMER DURABLE/],["INFRA",/INFRA/],["DEFENCE",/DEFENCE/],["PSU BANK",/PSU BANK/],["PRIVATE BANK",/PRIVATE BANK/]];return (m.find(x=>x[1].test(s))||["OTHER",/.*/])[0]}
function renderKpis(idx,bread,flows,mood){const n=idx.indices||[];const find=x=>n.find(i=>i.index===x);const nifty=find("NIFTY 50")||n[0],bank=find("NIFTY BANK"),vix=find("INDIA VIX");const b=bread||{};$("#kpis").innerHTML=[["NIFTY 50",nifty?.price,pct(nifty?.change_pct),nifty?.change_pct],["BANK NIFTY",bank?.price,pct(bank?.change_pct),bank?.change_pct],["INDIA VIX",vix?.price,pct(vix?.change_pct),vix?.change_pct],["FII / FPI",flows?.categories?.["FII/FPI"]?.net_cr,"₹ Cr net",flows?.categories?.["FII/FPI"]?.net_cr],["BREADTH",b.stocks,b.above_ema200_pct+"% > EMA200",b.above_ema200_pct]].map(x=>'<div class="glass kpi"><label>'+x[0]+'</label><strong class="'+(Number(x[3])>=0?"up":"down")+'">'+(x[1]==null?"—":num(x[1]))+'</strong><small>'+x[2]+'</small></div>').join("")}
function renderIndices(idx){const names=["NIFTY 50","NIFTY BANK","NIFTY NEXT 50","NIFTY 100","NIFTY 200","NIFTY 500","NIFTY MIDCAP 150","NIFTY SMALLCAP 250"];const n=idx.indices||[];$("#coreIndices").innerHTML=names.map(x=>{const o=n.find(i=>i.index===x);return o?card(x,o):""}).join("");$("#coreIndices").onclick=e=>{const c=e.target.closest(".index-card");if(c)openIndices(idx.indices||[],c.dataset.index)}}
function renderSectors(idx){const groups={};(idx.indices||[]).forEach(o=>{const b=sectorBucket(o.index);if(b==="OTHER"||o.change_pct==null)return;(groups[b]??=[]).push(o)});const rows=Object.entries(groups).map(([k,v])=>{v.sort((a,b)=>Math.abs(b.change_pct)-Math.abs(a.change_pct));const o=v[0];return{k,o,count:v.length}}).sort((a,b)=>b.o.change_pct-a.o.change_pct);$("#sectorGrid").innerHTML=rows.map(x=>'<div class="sector heat'+(x.o.change_pct>2?3:x.o.change_pct>0.75?2:x.o.change_pct>0.1?1:x.o.change_pct<-2?"n3":x.o.change_pct<-0.75?"n2":x.o.change_pct<-.1?"n1":"0")+'" data-sector="'+esc(x.k)+'"><div><b>'+esc(x.k)+'</b><small>'+x.count+' tracked indices</small></div><strong class="'+(x.o.change_pct>=0?"up":"down")+'">'+pct(x.o.change_pct)+'</strong><small>'+esc(x.o.index)+'</small></div>').join("");$("#sectorFresh").textContent="NSE · "+fresh(idx.updated);$("#sectorRadar").innerHTML='<div class="radar-list">'+rows.slice().sort((a,b)=>Math.abs(b.o.change_pct)-Math.abs(a.o.change_pct)).slice(0,8).map(x=>'<div class="radar-item"><b>'+esc(x.k)+'</b><span class="'+(x.o.change_pct>=0?"up":"down")+'">'+pct(x.o.change_pct)+'</span></div>').join("")+'</div>';$("#sectorGrid").onclick=e=>{const c=e.target.closest(".sector");if(c)openSector(idx.indices||[],c.dataset.sector)}}
function rows(items,mode){return (items||[]).slice(0,9).map(o=>'<div class="row"><div><b>'+esc(o.sym)+'</b><small>'+mode+(o.deliv!=null?" · delivery "+o.deliv+"%":"")+(o.tover_l!=null?" · ₹"+num(o.tover_l)+"L turnover":"")+'</small></div><strong class="'+(Number(o.chg)>=0?"up":"down")+'">'+pct(o.chg)+'</strong></div>').join("")}
function renderRadar(r){$("#accumulation").innerHTML=rows(r.accumulation,"high delivery");$("#volumeBlast").innerHTML=rows(r.volume_blast,"volume");$("#selling").innerHTML=rows(r.hidden_selling,"high delivery")}
function renderFlows(f,b){const c=f?.categories||{};$("#flows").innerHTML='<div class="panelbar"><div><b>FII / DII FLOW</b><small>'+esc(f?.date||"latest available")+'</small></div></div><div class="flow-grid">'+["FII/FPI","DII"].map(k=>{const o=c[k]||{};return '<div class="flow"><b>'+k+'</b><strong class="'+(o.net_cr>=0?"up":"down")+'">₹'+num(o.net_cr)+' Cr</strong><div class="bar"><i style="width:'+Math.min(100,Math.abs(o.net_cr)/120)+'%"></i></div><small>Buy ₹'+num(o.buy_cr)+' · Sell ₹'+num(o.sell_cr)+'</small></div>'}).join("")+'</div>';$("#breadth").innerHTML='<div class="panelbar"><div><b>MARKET BREADTH</b><small>'+fresh(b.updated)+'</small></div></div><div class="breadth-grid">'+[["Stocks covered",b.stocks],["Above EMA200",b.above_ema200_pct+"%"],["RSI > 60",b.rsi_above_60],["RSI < 40",b.rsi_below_40],["Near 52W high",b.near_52w_high],["Volume spike 2×",b.volume_spike_2x]].map(x=>'<div class="metric"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join("")+'</div>'}
function renderGlobal(g){$("#global").innerHTML=(g.items||[]).slice(0,15).map(o=>'<div class="global"><b>'+esc(o.name)+'</b><strong>'+num(o.price)+'</strong><small class="'+(o.chg_pct>=0?"up":"down")+'">'+pct(o.chg_pct)+'</small></div>').join("")}
function renderNews(n){$("#news").innerHTML=(n.items||[]).slice(0,9).map(o=>'<a href="'+esc(o.link||"#")+'" target="_blank" rel="noopener">'+esc(o.title)+'<small>'+esc(o.publisher||o.topic||"News")+' · '+fresh(o.published)+'</small></a>').join("")}
function renderEconomy(e){$("#economy").innerHTML=(e.ind||[]).slice(0,8).map(o=>'<div class="econ-item"><b>'+esc(o.name)+'</b><strong class="'+(o.dir==="up"?"up":"down")+'">'+esc(o.val)+'</strong><small>'+esc(o.sub)+'</small></div>').join("")}
function renderCrypto(c){$("#crypto").innerHTML=(c.top||[]).slice(0,8).map(o=>'<div class="row"><div><b>'+esc(o.symbol)+'</b><small>'+esc(o.name)+'</small></div><strong class="'+(o.chg_24h_pct>=0?"up":"down")+'">'+pct(o.chg_24h_pct)+'</strong></div>').join("")}
function drawSpark(c){const s=c?.syms?.NIFTY?.["1m"],svg=$("#spark");if(!s?.c?.length){svg.innerHTML="";return}const vals=s.c.filter(Number.isFinite);const mn=Math.min(...vals),mx=Math.max(...vals),w=900,h=160,p=8;const pts=vals.map((v,i)=>(i/(vals.length-1))*w+","+(h-p-((v-mn)/(mx-mn||1))*(h-2*p))).join(" ");svg.innerHTML='<polyline points="'+pts+'" fill="none" stroke="var(--teal)" stroke-width="2.5"/><line x1="0" y1="'+(h-p)+'" x2="'+w+'" y2="'+(h-p)+'" stroke="var(--line)"/>'}
function openIndices(list,focus){$("#drawerContent").innerHTML='<h3>All NSE indices</h3><input class="search" id="idxSearch" placeholder="Search index…"><table class="all-table"><thead><tr><th>INDEX</th><th>PRICE</th><th>DAY</th><th>PE</th><th>PB</th></tr></thead><tbody id="idxBody"></tbody></table>';const paint=q=>{$("#idxBody").innerHTML=list.filter(o=>!q||o.index.toLowerCase().includes(q.toLowerCase())).map(o=>'<tr><td>'+esc(o.index)+'</td><td>'+num(o.price)+'</td><td class="'+(o.change_pct>=0?"up":"down")+'">'+pct(o.change_pct)+'</td><td>'+esc(o.pe)+'</td><td>'+esc(o.pb)+'</td></tr>').join("")};paint(focus||"");$("#idxSearch").value=focus||"";$("#idxSearch").oninput=e=>paint(e.target.value);showDrawer()}
function openSector(list,sector){const a=list.filter(o=>sectorBucket(o.index)===sector).sort((x,y)=>Math.abs(y.change_pct)-Math.abs(x.change_pct));$("#drawerContent").innerHTML='<h3>'+esc(sector)+' · constituent indices</h3><p>'+a.length+' tracked NSE indices in this bucket.</p><table class="all-table"><thead><tr><th>INDEX</th><th>PRICE</th><th>DAY</th><th>52W POS</th></tr></thead><tbody>'+a.map(o=>{const pos=o.year_high&&o.year_low?(100*(o.price-o.year_low)/(o.year_high-o.year_low)).toFixed(0)+"%":"—";return '<tr><td>'+esc(o.index)+'</td><td>'+num(o.price)+'</td><td class="'+(o.change_pct>=0?"up":"down")+'">'+pct(o.change_pct)+'</td><td>'+pos+'</td></tr>'}).join("")+'</tbody></table>';showDrawer()}
function openStocks(){const r=cache.radar||{};$("#drawerContent").innerHTML='<h3>Stock radar</h3><p>Repository EOD radar from NSE delivery / turnover data.</p><div class="rows">'+rows(r.accumulation,"accumulation")+'</div><div style="height:18px"></div><div class="rows">'+rows(r.volume_blast,"volume blast")+'</div>';showDrawer()}
function openSectors(){const n=cache["indices-all"]?.indices||[];const groups={};n.forEach(o=>{const b=sectorBucket(o.index);if(b!=="OTHER"&&o.change_pct!=null)(groups[b]??=[]).push(o)});$("#drawerContent").innerHTML='<h3>Sector map</h3><div class="sector-grid">'+Object.entries(groups).sort((a,b)=>Math.abs(b[1][0].change_pct)-Math.abs(a[1][0].change_pct)).map(([k,v])=>{v.sort((a,b)=>Math.abs(b.change_pct)-Math.abs(a.change_pct));const o=v[0];return '<div class="sector heat'+(o.change_pct>1?2:o.change_pct>0?1:o.change_pct<-1?"n2":o.change_pct<0?"n1":"0")+'"><b>'+esc(k)+'</b><strong class="'+(o.change_pct>=0?"up":"down")+'">'+pct(o.change_pct)+'</strong><small>'+esc(o.index)+'</small></div>'}).join("")+'</div>';showDrawer()}
function showDrawer(){$("#drawer").classList.add("open");$("#drawer").setAttribute("aria-hidden","false")}function closeDrawer(){$("#drawer").classList.remove("open");$("#drawer").setAttribute("aria-hidden","true")}
async function boot(){try{const [idx,g,f,b,r,n,e,c,ss,po,cd]=await Promise.all(DATA.map(load));renderKpis(idx,b,f);renderIndices(idx);renderSectors(idx);renderRadar(r);renderFlows(f,b);renderGlobal(g);renderNews(n);renderEconomy(e);renderCrypto(c);drawSpark(cd);$("#updated").textContent="NSE "+fresh(idx.updated)+" · Yahoo "+fresh(g.updated);$("#footerFresh").textContent="NSE snapshot "+fresh(idx.updated);$("#date").textContent=new Date().toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});const score=(ss.top||[]).length;document.querySelectorAll(".status").forEach(x=>x.textContent="PIPELINE ONLINE · "+score+" scored stocks");}catch(err){console.error(err);$("#updated").textContent="data load error — check repository snapshots"}}
function tick(){const d=new Date();$("#clock").textContent=d.toLocaleTimeString("en-IN",{hour12:false});const h=d.getHours()+d.getMinutes()/60;$("#status").textContent=h<9.25?"PRE-OPEN":h<15.5?"MARKET OPEN":"MARKET CLOSED"}
document.addEventListener("click",e=>{if(e.target.matches("[data-close]"))closeDrawer();const b=e.target.closest("[data-open]");if(b){const k=b.dataset.open;if(k==="indices")openIndices(cache["indices-all"]?.indices||[]);if(k==="sectors")openSectors();if(k==="stocks")openStocks()}});$("#refresh").onclick=()=>boot();$("#theme").onclick=()=>{document.documentElement.classList.toggle("light");localStorage.setItem("as-theme",document.documentElement.classList.contains("light")?"light":"dark")};if(localStorage.getItem("as-theme")==="light")document.documentElement.classList.add("light");tick();setInterval(tick,1000);boot();