name: TG Bot Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 .github/scripts/tgtest.py
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
